spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ass?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: C1D0c5788600
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  main:
    allow-bean-definition-overriding: true
  aop:
    proxy-target-class: true
  jackson:
   serialization:
    fail-on-empty-beans: false
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: xxxxxxxxxx@qq.com #发送邮件的邮箱地址
    password: xxxxxxxxxx #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    properties.mail.smtp.port: 465 #端口号465或587
    from: xxxxxxxx@qq.com # 发送邮件的地址，和上面username一致
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
server:
  servlet:
    session:
      timeout: 24h
  port: 8888
